FROM golang:1.8.5-alpine3.6
MAINTAINER @recall704 https://github.com/recall704

RUN echo "http://mirrors.aliyun.com/alpine/v3.6/main" > /etc/apk/repositories && \
    echo "http://mirrors.aliyun.com/alpine/v3.6/community" >> /etc/apk/repositories
