FROM golang:1.8.5-alpine
MAINTAINER @recall704 https://github.com/recall704

RUN echo "http://mirrors.aliyun.com/alpine/v3.4/main" > /etc/apk/repositories && \
    echo "http://mirrors.aliyun.com/alpine/v3.4/community" >> /etc/apk/repositories
