FROM golang:1.8.5-alpine3.6
MAINTAINER @recall704 https://github.com/recall704

RUN apk update && \
    apk add gcc linux-headers musl-dev && \
    rm -rf /var/cache/* && \
    mkdir -p /var/cache/apk/ && \
    echo "https://mirrors.ustc.edu.cn/alpine/v3.6/main/" > /etc/apk/repositories && \
    echo "https://mirrors.ustc.edu.cn/alpine/v3.6/community/" >> /etc/apk/repositories
